### ISSUE TITLE
In use pin  <Unnamed>  no longer exists on node  Add Root Bone . Please refresh node or break links to remove pin.

### ISSUE THREAD

**Issue by colorindarkness** [tuatec/TTToolbox#13]
Error in BP_SkeletonBoneFunctions function Add Root Bone
![image](https://user-images.githubusercontent.com/9194221/179706520-c838fd87-b355-4e91-a135-2a9981a681a5.png)

**Comment by colorindarkness** [comment]
Windows 10 
Unreal Engine 5.0.3 Source Build

This occurs when updating an existing installed plugin

**Comment by AchimTuran** [comment]
Please wait until v0.4 is officially released then the issue should be gone, it seems to be an Unreal Engine issue. It will available during the next days. Basically when this gets merged to master, https://github.com/tuatec/TTToolbox/pull/12.

**Comment by colorindarkness** [comment]
Sorry I thought it was released (but you just renamed the branch)! I will now take look at your full implementation!

**Comment by AchimTuran** [comment]
Now v0.4 is already released. If you have further issues please do not hesitate to reopen this issue if you still have the same issue. 😉
