### ISSUE TITLE
Retarget ALS-Refactored

### ISSUE THREAD

**Issue by PaulNguyen88** [tuatec/TTToolbox#20]
I tried to retarget skelenton from als-refactored to paragon or other characterf ollow the instruction from your tuttorial. 
https://www.youtube.com/watch?v=DEpwDjWY2wI&list=PLslFX7TZAr89enRHIfJwUJJ_hJV8wX_8v&index=5
For other plugins like als-community or als original everything works great. But since the developer als-refactored has customized the virtual bone in the original, I have a hard time creating the constraint bone.
I dumbed ske's virtual bone in the als-refactored build:

`((VirtualBoneName="VB foot_root",SourceBoneName="root",TargetBoneName="root"),(VirtualBoneName="VB foot_l",SourceBoneName="VB foot_root",TargetBoneName="foot_l"),(VirtualBoneName="VB foot_r",SourceBoneName="VB foot_root",TargetBoneName="foot_r"),(VirtualBoneName="VB hand_l_to_hand_r",SourceBoneName="hand_l",TargetBoneName="hand_r"),(VirtualBoneName="VB hand_r",SourceBoneName="VB hand_l_to_hand_r",TargetBoneName="hand_r"),(VirtualBoneName="VB hand_l_to_ik_hand_gun",SourceBoneName="hand_l",TargetBoneName="ik_hand_gun"),(VirtualBoneName="VB ik_hand_r",SourceBoneName="VB hand_l_to_ik_hand_gun",TargetBoneName="hand_r"),(VirtualBoneName="VB hand_r_to_hand_r",SourceBoneName="hand_r",TargetBoneName="hand_r"),(VirtualBoneName="VB hand_l",SourceBoneName="VB hand_r_to_hand_r",TargetBoneName="hand_l"),(VirtualBoneName="VB hand_r_to_ik_hand_gun",SourceBoneName="hand_r",TargetBoneName="ik_hand_gun"),(VirtualBoneName="VB ik_hand_l",SourceBoneName="VB hand_r_to_ik_hand_gun",TargetBoneName="hand_l"))`

And here is the constraintbone that I created:
`((ConstraintBone="root",ModifiedBone="ik_foot_root"),(ConstraintBone="foot_l",ModifiedBone="ik_foot_l"),(ConstraintBone="foot_r",ModifiedBone="ik_foot_r"),(ConstraintBone="root",ModifiedBone="ik_hand_root"),(ConstraintBone="hand_r",ModifiedBone="ik_hand_gun"),(ConstraintBone="hand_r",ModifiedBone="ik_hand_r"),(ConstraintBone="hand_l",ModifiedBone="ik_hand_l"),(ConstraintBone="ik_foot_l",ModifiedBone="VB foot_l"),(ConstraintBone="ik_foot_r",ModifiedBone="VB foot_r"),(ConstraintBone="ik_hand_gun",ModifiedBone="VB hand_r_to_ik_hand_gun"),(ConstraintBone="ik_hand_gun",ModifiedBone="VB hand_l_to_ik_hand_gun"),(ConstraintBone="hand_r",ModifiedBone="VB ik_hand_r"),(ConstraintBone="hand_l",ModifiedBone="VB ik_hand_l"),(ConstraintBone="ik_foot_root",ModifiedBone="VB foot_root"),(ConstraintBone="foot_l",ModifiedBone="VB foot_l"),(ConstraintBone="foot_r",ModifiedBone="VB foot_r"),(ConstraintBone="ik_hand_l",ModifiedBone="VB ik_hand_l"),(ConstraintBone="hand_r",ModifiedBone="VB ik_hand_r"))`

The result is :(( : 
![image](https://user-images.githubusercontent.com/112599643/188297517-53a1bc8a-dcc0-4517-a50e-3ef73ab0c76f.png)

**Comment by AchimTuran** [comment]
What is the name of white bone that is facing upwards?

**Comment by AchimTuran** [comment]
Nother way to get the VBs working would be to use the force recompressing feature of TTToolbox. Did you try this already?

**Comment by PaulNguyen88** [comment]
> What is the name of white bone that is facing upwards?

I'm not sure if it is, before I tried to add the bone constraints it was `VB ik_hand_r` , but now it's `VB hand_l_to_ik_hand_gun = (VirtualBoneName="VB hand_l_to_ik_hand_gun",SourceBoneName="hand_l",TargetBoneName="ik_hand_gun") `.

**Comment by PaulNguyen88** [comment]
@AchimTuran You can download the project here: Is more clearly for understand. My IK_Rig is on the Folder GameContent->CharacterAssets->ALS or Gknight -> Rigs https://drive.google.com/file/d/1jeZhMcq3nxh2ljzmWbJtt2o8R7MqN4lR/

**Comment by AchimTuran** [comment]
@PaulNguyen88 
Thx for uploading the project will have a look at it during this evening and will get back to you once I know what is wrong. 😉

**Comment by AchimTuran** [comment]
> Can you guide me more clearly? I do not really understand that.

You can do a right click on the skeleton asset and let the editor run this script. Of course it only works for already stored anim sequences which are connected to the skeleton asset. I will soon add a new feature where you can run this script on individual anim sequences.
![image](https://user-images.githubusercontent.com/6927011/188302330-2cd97107-c4bb-4ba7-add0-579e3a1fe85f.png)

As this feature is not tested a lot across the community, please make a backup of your project in case something breaks. 😉

**Comment by AchimTuran** [comment]
Okay the hierarchy seems not to be supported by the solver currently. It might be a loop. Further analysis will be done in #21 if I find the time. This was the reason why I closed this one.

**Comment by AchimTuran** [comment]
I added a correct constraint for ALS Refactored data table row during the merge of #28. Will be available in v0.5 after #29 is merged back to master.

**Comment by PaulNguyen88** [comment]
Thanks you bro, I checked your new config for constraint bone, and look quite good in IK_Rigs. But unfortunely, the retarget results still failed. 
ALS refactored used control rig, I dont know what is wrong but the ik_hand bone still not mesh up with the Virtual Bone.
Once again, thank you very much for your contribution to the community :D
![image](https://user-images.githubusercontent.com/112599643/208816720-eef53778-86c9-4036-9f1d-7af7bace7da6.png)
