### ISSUE TITLE
foot ik do not work

### ISSUE THREAD

**Issue by Amegaku** [tuatec/TTToolbox#27]
I did everything according to the points
"https://github.com/tuatec/TTToolbox/issues/11"
not reacted.
![image](https://user-images.githubusercontent.com/33390318/201976122-8b45fd45-1467-4ab7-8ed8-4a8c8df818c1.png)
![image](https://user-images.githubusercontent.com/33390318/201976169-6f17b517-cc28-41b0-9fe4-94676740c353.png)

**Comment by AchimTuran** [comment]
Check that skeleton curves are not missing. I recommend watching my Mixamo and TwinBlsdt series. 😉
Normally you can transfer the steps to a MH as well.
Mixamo Retargeting Experiment - UE5 - TTToolbox
https://www.youtube.com/playlist?list=PLslFX7TZAr8_rp0_Oj5v6-8HlEvKU_JKw

The Truth of Retargeting in UE5 - Paragon TwinBlast
https://www.youtube.com/playlist?list=PLslFX7TZAr89enRHIfJwUJJ_hJV8wX_8v

Did it help to solve your issue?

**Comment by AchimTuran** [comment]
I assume the issue is solved, if it is not the case please reopen this issue. 😉
