### ISSUE TITLE
Malformed tags

### ISSUE THREAD

**Issue by steter** [tuatec/TTToolbox#31]
**Describe the bug**
Running UE 5.0 in Windows 11. After compiling with VS 2022, which had no errors, loading UE5 Editor throws malformed tag errors for everything in Content. So none of the uassets are available, and there is no functionality.

**To Reproduce**
0. Copied unzipped code into Plugins folder in project.
1. Built the code using a sln file
2. Started the editor
3. Looked in the logs
4. Saw errors, and none of the scripts were available

**Expected behavior**
That it would compile and run.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v0.4

**Additional context**
Example of error:
LogAssetRegistry: Error: Package E:/Games/Unreal Projects/ALS_5_0/Plugins/TTToolbox-master/Content/Structures/ST_TTVirtualBones.uasset has malformed tag

**Comment by steter** [comment]
Well, this one's on me. The pre-built code runs fine. You already know there's something up with 5.0 builds. My bad.

**Comment by steter** [comment]
Not an issue for the pre-built code.

**Comment by AchimTuran** [comment]
You're welcome. No problem the system is quite complex and you should be happy that you figured it out on your own. ;-)
