### ISSUE TITLE
Crash when adding virtual bones

### ISSUE THREAD

**Issue by woodencase01** [tuatec/TTToolbox#40]
**Describe the bug**
I'm following the video tutorials and using TTToolbox 0.5 with the IKRig V1.1 fix for Unreal 5.1.
At the step of using the script to add the virtual bones, the engine crash.
I also tried to manually add the virtual bones, and it also crash.
I'm using the Synty skeleton here. It has a few missing finger bones due to the simplified look.
![image](https://user-images.githubusercontent.com/4787041/227718895-08ceb7d3-edc5-4de6-b0d6-c85aa2c51cf9.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/4787041/227718832-a6d73a2b-fd16-439b-bb33-716e703d6942.png)

or

![image](https://user-images.githubusercontent.com/4787041/227718815-80440441-faa2-40f2-bddf-3ac59faa0600.png)

**Expected behavior**
Should add the bone.

**Screenshots**
```
Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\Core\Public\Containers\Array.h] [Line: 763] Array index out of bounds: 56 from an array of size 56

UnrealEditor_IKRig!FAnimNode_RetargetPoseFromMesh::Evaluate_AnyThread() [C:\workspace\zz_tutorials\Fixing_IKRig\zz_packaging\IKRig_v1.1_UE5.1_win64_release\HostProject\Plugins\IKRig\Source\IKRig\Private\AnimNodes\AnimNode_RetargetPoseFromMesh.cpp:129]
UnrealEditor_Engine
```

**Comment by AchimTuran** [comment]
I would need the mesh to reproduce the issue. Sadly this did not yet ever happen to me.

**Comment by woodencase01** [comment]
Thanks for your feedback and support!

I forgot to get back to this thread, but I found a solution.
Neither the TTToolbox or the IKRig fix are the cause here, as I could do it on other skeleton.

The solution was:
Duplicate the skeleton, make sure no animations are attached.
Create the virtual bones.
Retarget animation from ALS to the new skeleton.
Profit.

Thanks for your videos, I'm following them one by one and it's great to understand and slowly progress! I'm not a big fan of the copy pose from mesh result, thus retargeting ALS is much appreciated.
