### ISSUE TITLE
UE5.0.3 creates an assertion while adding unweighted bones to a metahuman

### ISSUE THREAD

**Issue by AchimTuran** [tuatec/TTToolbox#5]
Member lAKKWHY reported the issue here, https://discord.com/channels/671128082110742561/762949358417084426/996773343514599494

And gave detailed information about the occuring error message here, https://discord.com/channels/671128082110742561/762949358417084426/996958332776616038
```
Assertion failed: (Index >= 0) & (Index < ArrayNum)
[File:D:\build++UE5\Sync\Engine\Source\Runtime\Core\Public\Containers\Array.h] [Line: 691] Array index out of bounds: -1 from an array of size 359

UnrealEditor_Engine 
i Get this error message from TTToolbox-unweighted-bones plugin
```

[AdvancedLocomotionSystemV.log](https://github.com/tuatec/TTToolbox/files/9108866/AdvancedLocomotionSystemV.log)

**Comment by AchimTuran** [comment]
I tested the latest state of the unweighted feature branch with 5.0.3
![grafik](https://user-images.githubusercontent.com/6927011/178908601-42be1f72-b0b3-4bc9-9985-9c7485d4e94a.png)
Mixamo character seems still to work fine
![grafik](https://user-images.githubusercontent.com/6927011/178908631-4d04241a-b848-4acb-9d90-a060a2232e7f.png)

Quoted from: https://discord.com/channels/671128082110742561/762949358417084426/997011808697196607

**Comment by AchimTuran** [comment]
MetaHuman Hudson worked so far as well
![grafik](https://user-images.githubusercontent.com/6927011/178908938-450525c4-9e15-4170-851b-36c50f7b8d2a.png)
![grafik](https://user-images.githubusercontent.com/6927011/178908865-126497f6-2c5d-47d8-8725-3f993ffb5e3c.png)

**Comment by AchimTuran** [comment]
Hmmm I need the exact same MetaHuman and the exact steps that were used to create the issue. I can not reproduce the issue locally on my machine. 😞

**Comment by AchimTuran** [comment]
I'm getting this issue when I add the required virtual bones for ALS and then try to add the unweighted bones that I get this assertion as well.
![grafik](https://user-images.githubusercontent.com/6927011/178916589-e55a07d3-56e7-4e81-80d1-266a785620fa.png)

@ lAKKWHY
Please remove the virtual bones and try again.

**Comment by lakkyhb** [comment]
Hello here @ lAKKWHY
i,m using HANA metahuman.
I uploaded a video on discord channel  [https://discord.com/channels/671128082110742561/762949358417084426/997050379713916980](url)
Virtual Bones added not working showing in Metahuman character. you can see in video.
Editor is not crashing when i recorded this video, because unweighted bones already exists i think!!

**Comment by AchimTuran** [comment]
I added some fixes to this issue in the unweighted bones feature branch, see https://github.com/tuatec/TTToolbox/pull/2#issuecomment-1184830606. In my case it fixed the wrong bone index access. Details can be found here, https://github.com/tuatec/TTToolbox/pull/2#issuecomment-1184826956.

**Comment by lakkyhb** [comment]
OK I'm checking

**Comment by AchimTuran** [comment]
For me the issue was resolved, which is the reason why I now close this ticket here. If you still have the issue feel free to reopen and we will have a look at it again. 😉

I wish you all the success within your character integration journey. 💪
