### ISSUE TITLE
**Describe the bug**nb    قحبة جواهر

### ISSUE THREAD

**Issue by b7r3333** [tuatec/TTToolbox#50]
**Describe the bug**
Adding virtual bones for a skeleton with existing anim sequences crash the editor.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. v0.4]

**Additional context**

_Originally posted by @AchimTuran in https://github.com/tuatec/TTToolbox/issues/42_

**Comment by AchimTuran** [comment]
It is unclear what the feature request is. If you have a more clear description do not hesitate to write it down here and open the ticket again.
