### ISSUE TITLE
[Feature Request]  UE 5.4 Support

### ISSUE THREAD

**Issue by ScoobyBaby** [tuatec/TTToolbox#59]
ALS Refactored has its utility plugins to get started but community does not...
ive been relying on yours to get my ALS retargeted but after upgrading to 5.4 it broke and dont know how to fix...

Any plans to update? 5.4 has lots of new features for ik retargeting

**Comment by ScoobyBaby** [comment]
Until tuatec updates it to 5.4 i recommend for everyone to use Free Bone Snapper plugin from the marketplace, you need it for ik bone constraint. You have to set everything up manually you need it for ALS retargetting

**Comment by AchimTuran** [comment]
#60 will bring UE5.4 support

**Comment by AchimTuran** [comment]
UE 5.4 Support went into https://github.com/tuatec/TTToolbox/releases/tag/v0.6.
