### ISSUE TITLE
minor bug, TTToolbox_v0.6_UE5.4_win64_release.zip corrupt.

### ISSUE THREAD

**Issue by ScoobyBaby** [tuatec/TTToolbox#61]
Upon downloading the file mentioned above from the latest release, an error message pop up says that the file is invalid, and empty? although it does have a file size, therefore it cannot be opened nor uncompressed.

This bug also corrupt the 5.3 file aswell!

1. Go to https://github.com/tuatec/TTToolbox/releases/tag/v0.6
2. Click on [TTToolbox_v0.6_UE5.4_win64_release.zip](https://github.com/tuatec/TTToolbox/releases/download/v0.6/TTToolbox_v0.6_UE5.4_win64_release.zip)
or 
[TTToolbox_v0.6_UE5.3_win64_release.zip](https://github.com/tuatec/TTToolbox/releases/download/v0.6/TTToolbox_v0.6_UE5.3_win64_release.zip)

when file is double clicked:
![Screenshot 2024-08-12 124147](https://github.com/user-attachments/assets/02e92c12-8cfa-456a-97e1-851be8ffc71f)

 - OS: Windows11
 - Version v0.6

**Comment by AchimTuran** [comment]
hmmm ... not sure what tar.exe does in detail, something seems to have changed...
I was able to open the files with 7z but not with the Windows Internal Explorer Tool.

Anyways @ScoobyBaby  thx for reporting, I changed the scripts and uploaded the files again. It should work now. Feel free to reopen if there are more issues to zipping the builds. 😊
